# Generated by Django 2.2.13 on 2021-04-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed', '0002_beddata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldata',
            name='name',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Hospital Name'),
        ),
    ]
