# Generated by Django 2.2.13 on 2021-04-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bed', '0004_hospitaldata_bed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beddata',
            options={'ordering': ('-created_at',), 'verbose_name': 'Hospital Bed data'},
        ),
        migrations.RenameField(
            model_name='beddata',
            old_name='type',
            new_name='hospital_type',
        ),
        migrations.RenameField(
            model_name='hospitaldata',
            old_name='type',
            new_name='hospital_type',
        ),
    ]
