# Generated by Django 2.2.13 on 2021-04-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed', '0005_auto_20210428_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='beddata',
            name='bed_type',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Bed Types'),
        ),
    ]
