# Generated by Django 2.2.13 on 2021-04-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed', '0006_beddata_bed_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaldata',
            name='map_link',
            field=models.URLField(blank=True, max_length=840, null=True, verbose_name='Hospital contact number'),
        ),
    ]
